# Generated by Django 5.0.1 on 2024-10-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uauthentic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='otp',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
